version: "3.7"

services:
  app_microservice:
    image: ${DOCKER_REGISTRY}/zinov/app_microservice:${VERSION}
    environment:
      APP_MICROSERVICE_ENV: dev
      APP_MICROSERVICE_V7_ELASTIC_SNIFF: "true"
      APP_MICROSERVICE_STORAGE_DB_USER: ${APP_MICROSERVICE_STORAGE_DB_STAGE_USER}
      APP_MICROSERVICE_STORAGE_DB_PASSWORD: ${APP_MICROSERVICE_STORAGE_DB_STAGE_PASSWORD}
      APP_MICROSERVICE_STORAGE_DB_HOST: ${APP_MICROSERVICE_STORAGE_DB_STAGE_HOST}
      APP_MICROSERVICE_STORAGE_DB_PORT: ${APP_MICROSERVICE_STORAGE_DB_STAGE_PORT}
      APP_MICROSERVICE_STORAGE_DB_NAME: ${APP_MICROSERVICE_STORAGE_DB_STAGE_NAME}
      APP_MICROSERVICE_V7_ELASTIC_URL: ${APP_MICROSERVICE_V7_ELASTIC_STAGE_URL}
      APP_MICROSERVICE_V7_ELASTIC_LOGIN: ${APP_MICROSERVICE_V7_ELASTIC_STAGE_LOGIN}
      APP_MICROSERVICE_V7_ELASTIC_PASSWORD: ${APP_MICROSERVICE_V7_ELASTIC_STAGE_PASSWORD}
      APP_MICROSERVICE_APISERVER_CORS_ORIGIN: ${APP_MICROSERVICE_APISERVER_CORS_ORIGIN}
      APP_MICROSERVICE_APISERVER_CORS_HEADERS: ${APP_MICROSERVICE_APISERVER_CORS_HEADERS}
      APP_MICROSERVICE_APP_SERVICE_BASE_URL: ${APP_MICROSERVICE_SCHEDULE_SERVICE_STAGE_URL}
      APP_MICROSERVICE_CMN_BASE_URL: ${APP_MICROSERVICE_CMN_BASE_STAGE_URL}
      APP_MICROSERVICE_S3_ACCESS_KEY_ID: ${APP_MICROSERVICE_S3_ACCESS_KEY_ID}
      APP_MICROSERVICE_S3_ACCESS_KEY_SECRET: ${APP_MICROSERVICE_S3_ACCESS_KEY_SECRET}

      JAEGER_AGENT_HOST: ${JAEGER_AGENT_TEST}
      JAEGER_SAMPLER_TYPE: remote
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_SERVICE_NAME: app_microservice
    stop_grace_period: 1m
    command: ["/usr/local/bin/app_microservice"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "${APP_MICROSERVICE_EXTERNAL_PORT}:8080"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_HAPROXY_HOST_TEST}:${FLUENTD_HAPROXY_PORT}
        fluentd-async-connect: "true"
        fluentd-retry-wait: "2s"
        fluentd-max-retries: "60"
        mode: non-blocking
        tag: ${FLUENTD_TAG}.${CI_COMMIT_REF_SLUG}
    networks:
      - app_microservice

networks:
  app_microservice: