version: "2.4"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: 'app_microservice'
      POSTGRES_USER: 'app_microservice'
      POSTGRES_PASSWORD: 'app_microservice'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD", "pg_isready" ,"-U", "app_microservice" ]
      timeout: 5s
      retries: 10
    networks:
      - app_microservice

networks:
  app_microservice:
    driver: bridge